### ISSUE TITLE
Abstract text has run on words

### ISSUE THREAD

**Issue by etattershall** [Mahdisadjadi/arxivscraper#1]
Hi! Thank you for the wonderful code - it's the best one I've seen for grabbing specific categories! 

There's a minor bug in the get text function though that is causing words on either side of newlines to be smushed together:

    def _get_text(self, namespace, tag):
        """Extracts text from an xml field"""
        try:
            return self.xml.find(namespace + tag).text.strip().lower().replace('\n', '')
        except:
            return ''

Should replace newlines with a space rather than an empty string

replace('\n', '') --> replace('\n', ' ')

**Comment by Mahdisadjadi** [comment]
Hi @etattershall! Thanks for your kind words and finding this bug! It should be fixed now.
