### ISSUE TITLE
Update python package to deal with name NoneType error.

### ISSUE THREAD

**Issue by lmcnichols** [Mahdisadjadi/arxivscraper#11]
I run into an error on fetching the names
![image](https://user-images.githubusercontent.com/52261474/92257077-7dfec400-ee89-11ea-9ff5-788b584f4395.png)

It looks like you already fixed this in the repo. Can you publish the latest version?

**Comment by Mahdisadjadi** [comment]
@lmcnichols : The latest version is published to `pip` (`pip install arxivscraper=0.0.4`) .
