### ISSUE TITLE
How to extract full name of author

### ISSUE THREAD

**Issue by bigheiniu** [Mahdisadjadi/arxivscraper#2]
Hi, thanks for sharing your excellent scraper. 
Currently, I want to extract the full name of the authors, however, your program just extracts the authors' first name. Even I add this  
`
    authors_lastName =[author.find(ARXIV + 'forenames').text.lower() if not  author else "_" for author in authors]
`
The output just contains the authors first name

**Comment by Mahdisadjadi** [comment]
@bigheiniu : Thank you for your kind comment. 
The program extracts the last name by default. I updated the code to fetch the full name. Could you give a test and see if that is what you want?

**Comment by Mahdisadjadi** [comment]
PR #9 should have resolved this. Closing the issue.
