### ISSUE TITLE
ImportError: No module named arxivscraper

### ISSUE THREAD

**Issue by matt-davis27** [Mahdisadjadi/arxivscraper#3]
I am unable to import arxivscraper when downloading using pip but can use the package just fine when downloading it as a zip and storing it in the current directory.

arxivscraper version 0.0.2
python 2.7.10
Command entered "import arxivscraper" from git READ.ME
Error message "ImportError: No module named arxivscraper"

**Comment by Mahdisadjadi** [comment]
@matt-davis27 Thanks for raising the issue. I can reproduce this and will fix this soon!

**Comment by davebulaval** [comment]
Same bug. `ModuleNotFoundError: No module named 'arxivscraper'`

**Comment by Mahdisadjadi** [comment]
@matt-davis27 , @davebulaval : Thank you for the feedback. 

I updated the setup file which could not find the package properly. The bug should be fixed after the update. Could you try `pip install -U arxivscraper` to test it?

**Comment by davebulaval** [comment]
@Mahdisadjadi work for me.

**Comment by matt-davis27** [comment]
Works for me as well! Successfully installed arxivscraper-0.0.3
I will mark this thread as closed. Thanks @Mahdisadjadi

**Comment by Mahdisadjadi** [comment]
@davebulaval and @matt-davis27 : Awesome! Thanks for testing.
